# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_OPTEE) += optee.o
optee-objs += core.o
optee-objs += call.o
optee-objs += rpc.o
optee-objs += supp.o
optee-objs += shm_pool.o
optee-objs += grpc.o

CFLAGS_optee.o = -O0
CFLAGS_core.o = -O0
CFLAGS_call.o = -O0
CFLAGS_rpc.o = -O0
CFLAGS_supp.o = -O0
CFLAGS_shm_pool.o = -O0
CFLAGS_grpc.o = -O0
